### ISSUE TITLE
deployTargetServer receives error (404) but returns "Updated targetserver"

### ISSUE THREAD

**Issue by brandonverzuu-appythings** [appythings/apigee-apim#18]
During the usage of **deployTargetServer** in a Hybrid setup, the tool receives a 404 from Apigee API but returns "Updated TargetServer: [TARGETSERVER]" response.

_Note: the [apigee-apim-jenkins-targetServer-error.log file](https://github.com/appythings/apigee-apim/files/7793301/apigee-apim-jenkins-targetServer-error.log) has sensitive information masked. E.g. Apigee Organization = \*\*ORG\*\*. Format used in orgs and envs is [PILLAR]-[INTERNAL]-[NAME]-[INSTANCE]_

**Comment by reiniervanderhoeven** [comment]
Fixed in https://github.com/appythings/apigee-apim/pull/19
